name: Get VPS
version: "1.3.1"
slug: get
image: "ghcr.io/Vioneta/{arch}-addon-get"
description: The easiest way to get VPS for Vioneta Agro
startup: once
boot: manual
url: "https://github.com/Vioneta/addons-vps/tree/main/get"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
schema:
  channel: list(current|development)?
map:
  - homeassistant_config:rw
